### PR TITLE
Fix at and in chainable methods

### PR DESCRIPTION
**Pull request by wpolicarpo**
Fixes https://github.com/philostler/rspec-sidekiq/issues/107.

### CODE REVIEW

**Comment by packrat386** [comment]
👍

**Comment by packrat386** [comment]
@wpolicarpo is this ready to get merged in?

**Comment by wpolicarpo** [comment]
@packrat386 need to take a look at those error messages, but I'm out of time lately. I'll try to do it this week.

**Comment by philostler** [comment]
@wpolicarpo Error? Ci passed OK didn't it?

**Comment by wpolicarpo** [comment]
@packrat386 @philostler sorry, I was talking about this: https://github.com/philostler/rspec-sidekiq/issues/107#issuecomment-250600459.

It should be fine now, I guess.

**Comment by wpolicarpo** [comment]
@packrat386 @philostler can we merge this?

**Pull request merged**
