### PR TITLE
Fix clash with rspec-rails

### PR DESCRIPTION
**Pull request by pavel-jurasek-bcgdv-com**
This PR fix clash with rspec-rails

### CODE REVIEW

**Comment by philostler** [comment]
Hi @pavel-jurasek-bcgdv-com , is this in addition to #84 or an improved version of?

**Comment by pavel-jurasek-bcgdv-com** [comment]
- Add ability to match symbols
- Fix matcher with combination with ActiveJob

**Comment by philostler** [comment]
Thanks @pavel-jurasek-bcgdv-com . Merged!

**Comment by bk-one** [comment]
Can we get a backport of that in `rspec-sidekiq` 2.x? Or is 3.0 coming in the foreseeable future? Happy to provide a patch

**Comment by bk-one** [comment]
https://github.com/philostler/rspec-sidekiq/pull/108

**Pull request merged**
