### PR TITLE
Add support for testing scheduled jobs

### PR DESCRIPTION
**Pull request by wpolicarpo**
Allow you to test scheduled jobs chaining `#at` to `#have_enqueued_job`.

```ruby
Awesomejob.perform_at 5.minutes, 'Awesome', true
# test with...
expect(AwesomeJob).to have_enqueued_job('Awesome', true).at(5.minutes)
```

I don't know if this is the best approach, but it's a start.
Suggestions are welcome.

### CODE REVIEW

**Comment by RobinDaugherty** [comment]
I love the idea. I'd like to point out that according to the sidekiq docs, `perform_in` is used for an offset of time, which `perform_at` expects an exact time. So the chainable method you've added, `at`, seems to be misnamed based on your examples.

I think that in your example, you are setting the job to execute at `1970-01-01 00:05:00` but the way you've documented it, that's unclear. So I would suggest updating the documentation and your example in this PR.

Perhaps we should also add an `in` chainable method that accepts a time offset instead of a full time.

**Comment by wpolicarpo** [comment]
You're right, @RobinDaugherty.

I'll add an `in` chainable method and update both README and description.

**Comment by urkle** [comment]
This was the feature I was hoping was in this gem.  Any idea on timeline to get it in there?

**Comment by philostler** [comment]
@wpolicarpo Can you resolve the conflicts and I'll go for the merge?

**Comment by wpolicarpo** [comment]
@philostler I resolved the conflicts and added support for `perform_in` as well.

Please, take a look.

**Comment by philostler** [comment]
Sorry @wpolicarpo. Can you rebase again and we'll get this in. Thanks

**Comment by philostler** [comment]
Cheers @wpolicarpo

**Pull request merged**
